### ISSUE TITLE
unhandled response

### ISSUE THREAD

**Issue by AbyssMorgan** [xofred/deviantart-gallery-downloader#28]
Today i got following error
```
Updating netrc's entry
Logging in
403 => Net::HTTPForbidden for https://www.deviantart.com/users/login -- unhandled response
Login failed after 3 retries
You might not be able to fetch the age restricted resources
Connecting to gallery
gallery has no images, abort
```

**Comment by xofred** [comment]
If you don't mind, could you please provide the DeviantArt gallery link? Because on my end, everything seems ok...
<img width="822" alt="downloading" src="https://user-images.githubusercontent.com/2174219/117338990-cb787880-aed1-11eb-8f5c-9d18da33624b.png">
<img width="816" alt="folder" src="https://user-images.githubusercontent.com/2174219/117339012-d3d0b380-aed1-11eb-9936-34c9a2d0fd46.png">

**Comment by AbyssMorgan** [comment]
I fixed issue after reinstall gem dependencies
```
gem install addressable
gem install domain_name
gem install http-cookie
gem install mime-types
gem install net-http-digest_auth
gem install net-http-persistent
gem install nokogiri
gem install rubyntlm
gem install webrick
gem install webrobots
```
